name: lozano
favicon: null
layout_spectrum: 0.9527442445978522
typography_spectrum: 0.17802354134619236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7649896391667426
  lightness: 0.7128458488732576
  saturation: 0.8030790188349783
  rhythmicContrast: 0.5494423324707896
purpose: []
